_target_: newsreclib.models.general_rec.miner_module.MINERModule

# training strategy
dual_loss_training: False
dual_loss_coef: null
loss: "cross_entropy_loss"
late_fusion: False
temperature: None

# news encoder
dataset_attributes: ${data.dataset_attributes}
attributes2encode: ["title"]

# text encoder
use_plm: True
plm_model: null
frozen_layers: null
apply_reduce_dim: True
text_embed_dim: 768
news_embed_dim: 256
dropout_probability: 0.2
use_categ_bias: True
pretrained_categ_embeddings_path: null
num_context_codes: 32
context_code_dim: 200
score_type: "weighted" # choose between weighted, mean, max

# outputs
outputs:
  train: ["preds", "targets", "cand_news_size"]
  val: ["preds", "targets", "cand_news_size"]
  test:
    [
      "preds",
      "targets",
      "cand_news_size",
      "hist_news_size",
      "target_categories",
      "target_sentiments",
      "hist_categories",
      "hist_sentiments",
    ]

# evaluation
num_categ_classes: 18
num_sent_classes: 3

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0001

scheduler: null
